import Head from 'next/head'
import { initialState } from '../redux/allReducers';
import { useState } from 'react'
import { useSelector, useDispatch } from 'react-redux'
import { add, subtract } from '../redux/allReducers'
import styles from '../styles/Home.module.css'

 

export default function Home() {
  const [count, setCount] = useState(0)
  const stateInt = useSelector((state: initialState) => state.count)
  const dispatch = useDispatch()
  const handleAdd = () => {
    setCount((count) => count + 1)
    dispatch(add())
  }
  const handleSubtract = () => {
    setCount((count) => count - 1)
    dispatch(subtract())
  }
  const functionalState = () => {
    return (
      <div>
        <p>You clicked {count} times</p>
        <button onClick={() => setCount(count + 1)}>Click me</button>
      </div>
    )
  }
  const disfunctionalState = () => {
    return (
      <div className={styles.description}>
        <button onClick={() => handleAdd()}>+</button>
        <h1>Count: {count}</h1>
        <h1>State: {stateInt}</h1>
        <button onClick={() => handleSubtract()}>-</button>
      </div>
    )
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>{disfunctionalState()}</div>
      </main>
    </div>
  )
}
